FROM python:latest

WORKDIR /usr/src/app

COPY Pipfile.* ./
RUN pipenv install --dev

COPY . .

EXPOSE 400

ENV FLASK_APP=app \
    FLASK_ENV=Development \
    FLASK_DEBUG=True

CMD ["pipenv", "run", "flask", "run", --port=4000]