"""Adicionar tabelas

Revision ID: cbc6898b6896
Revises: 
Create Date: 2023-11-18 18:03:02.591700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbc6898b6896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('disciplina')
    op.drop_table('enum_acesso')
    op.drop_table('alunodisciplina')
    op.drop_table('user')
    op.drop_table('alunos')
    op.drop_table('responsavel')
    op.drop_table('conteudo')
    op.drop_table('endereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('idEndereco', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cep', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('rua', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idEndereco'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conteudo',
    sa.Column('idDiciplina', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idConteudo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.Column('nome', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['idDiciplina'], ['disciplina.idDisciplina'], name='conteudo_ibfk_1'),
    sa.PrimaryKeyConstraint('idConteudo', 'idDiciplina'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('responsavel',
    sa.Column('idResponsavel', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('idResponsavel'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alunos',
    sa.Column('idAluno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idResponsavel', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instituicao', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('serie', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('pretProfissional', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('idEndereco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idEndereco'], ['endereco.idEndereco'], name='alunos_ibfk_3'),
    sa.ForeignKeyConstraint(['idResponsavel'], ['responsavel.idResponsavel'], name='alunos_ibfk_2'),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.idUsuario'], name='alunos_ibfk_1'),
    sa.PrimaryKeyConstraint('idAluno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('idUsuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('acesso_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acesso_id'], ['enum_acesso.id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('idUsuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alunodisciplina',
    sa.Column('idDiciplina', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idaluno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idDiciplina'], ['disciplina.idDisciplina'], name='alunodisciplina_ibfk_1'),
    sa.ForeignKeyConstraint(['idaluno'], ['alunos.idAluno'], name='alunodisciplina_ibfk_2'),
    sa.PrimaryKeyConstraint('idDiciplina', 'idaluno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enum_acesso',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nivel_acesso', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('disciplina',
    sa.Column('idDisciplina', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cdgDisciplina', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['idProfessor'], ['professor.idProfessor'], name='disciplina_ibfk_1'),
    sa.PrimaryKeyConstraint('idDisciplina'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('professor',
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idUsuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.idUsuario'], name='professor_ibfk_1'),
    sa.PrimaryKeyConstraint('idProfessor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
